### ISSUE TITLE
Como instalar ?

### ISSUE THREAD

**Issue by luizjamp** [cortezfelipe/adianti-oauth-google#5]
Salvei local, e esta funcionando normalmente como a ultima versão do adiante.
Onde tenho que configurar para autenticar com a conta google ?

**Comment by cortezfelipe** [comment]
Entre com o usuário admin normal do template e adiciona um usuário com seu e-mail Google. A validação é feita pelo email.

**Comment by cortezfelipe** [comment]
Respondida
